### ISSUE TITLE
01/15/2020 session

### ISSUE THREAD

**Issue by angel-mora** [Dandush03/embedding-images-and-video#2]
Mike explained they had to re-do everything because code was not properly structured. 
He pulled the code again to get the latest changes as he required to do so in order to explain their progress within navbar and related videos. They added the buttons and tags as well.
They say CSS is almost done. Still have to inline like buttons for comments and some other small details for the comments section

**Comment by Dandush03** [comment]
it's not an issue. it's comment of the daily morning meeting of the Microverse Community.
